VERZIJA=CDX
MODUL=ka_1adm

SRCDOSROOT=$(BASEDOS)\\fmk\\kalk\\adm\\1g\\

PRGS=gen_9999.prg kor_nc.prg mnu_adm.prg rob_id.prg set_m10.prg sifk.prg
CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper

