VERZIJA=CDX
MODUL=ka_1adm

SRCDOSROOT=c:\\dev\\fmk\\kalk\\adm\\1g\\

PRGS=gen_9999.prg kor_nc.prg mnu_adm.prg rob_id.prg set_m10.prg sifk.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

