VERZIJA=CDX
MODUL=ka_p1gd


SRCDOSROOT=c:\\dev\\fmk\\kalk\\prod\\gendok\\1g\\

PRGS=gen_dok.prg pst.prg preknj.prg nivel.prg

CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

