VERZIJA=CDX
MODUL=ka_1dok


SRCDOSROOT=c:\\dev\\fmk\\kalk\\dok\\1g\\

PRGS=mnu_dok.prg frm_ldok.prg knjiz.prg rpt_ldok.prg rpt_prip.prg

CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

