VERZIJA=CDX
MODUL=ka_1dok

SRCDOSROOT=$(BASEDOS)\\fmk\\kalk\\dok\\1g\\

PRGS=mnu_dok.prg frm_ldok.prg knjiz.prg rpt_ldok.prg rpt_prip.prg

CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper

