VERZIJA=CDX
MODUL=ka_p1dok

SRCDOSROOT=c:\\dev\\fmk\\kalk\\prod\\dok\\1g\\

PRGS=frm_11.prg frm_12.prg frm_41.prg frm_80.prg frm_19.prg frm_81.prg frm_all.prg frm_ip.prg rpt_11.prg rpt_11_3.prg rpt_11nc.prg rpt_19.prg rpt_41.prg rpt_80.prg rpt_41p.prg

CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

