VERZIJA=CDX
MODUL=ka_m1rpt

SRCDOSROOT=c:\\dev\\fmk\\kalk\\mag\\rpt\\1g\\

PRGS=frm_kart.prg frm_kmag.prg mnu_izvj.prg rpt_fllm.prg rpt_kmag.prg rpt_llm.prg rpt_pgp.prg rpt_pru.prg rpt_rdob.prg rpt_reap.prg rpt_rflm.prg rpt_rpp.prg rpt_rpt.prg rpt_uob.prg

CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

