VERZIJA=CDX
MODUL=ka_m2rpt

include /sclib/Makefile_clipper

SRCDOSROOT=h:\\dev\\fmk\\kalk\\mag\\rpt\\2g\\

PRGS=rpt_lag.prg

CS=
ASMS=

OBJS=$(OBJPRGS) $(OBJCS) $(OBJASMS)

all: $(OBJS)
	rm -f $(MODUL).lib 
	$(LIBEXE) $(MODUL) $(LIBCMD) ,,
	cp $(MODUL).lib $(LIB_DEST)
	
clean:
	rm -f *~
	rm -f *.xref
	rm -f *.xrefs
	rm -f *.html
	rm -f *.OBJ *.obj
	rm -f xref_files
	rm -f $(OBJS) *.bak *.BAK


