VERZIJA=CDX
MODUL=ka_m1dok


SRCDOSROOT=c:\\dev\\fmk\\kalk\\mag\\dok\\1g\\

PRGS=frm_10.prg frm_10p.prg frm_14.prg frm_14p.prg frm_16.prg frm_16p.prg frm_18.prg frm_82.prg frm_94.prg frm_95.prg frm_im.prg frm_15.prg rpt_10.prg rpt_10p.prg rpt_10nc.prg rpt_10sk.prg rpt_14.prg rpt_18.prg rpt_82.prg rpt_95nv.prg rpt_95sk.prg rpt_im.prg rpt_15.prg rpt_14p.prg rpt_95p.prg

CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

