VERZIJA=CDX
MODUL=ka_1rpt

SRCDOSROOT=$(BASEDOS)\\fmk\\kalk\\rpt\\1g\\

PRGS=mnu_rpt.prg proizv.prg rpt_all.prg rpt_spo.prg rpt_pdv.prg rpt_exp.prg

CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper

