VERZIJA=CDX
MODUL=ka_s1pf


SRCDOSROOT=c:\\dev\\fmk\\kalk\\specif\\planika\\1g\\

PRGS=planika.prg rpt_fobm.prg db.prg db_gen1.prg db_gen2.prg db_cre.prg rpt_all.prg rpt_oinv.prg rpt_pkz.prg rpt_ppp.prg rpt_dnpr.prg rpt_rekp.prg mnu_sif.prg gen_pnc.prg pl_sif.prg

CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

