VERZIJA=CDX
MODUL=ka_1rdb

SRCDOSROOT=$(BASEDOS)\\fmk\\kalk\\razdb\\1g\\

PRGS=fak_kal.prg fin.prg gen_fakt.prg ka_ka.prg kont_dok.prg tops.prg tops_ka.prg mnu_raz.prg imp_txt.prg imp_csv.prg

CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper

