VERZIJA=CDX
MODUL=ka_1rdb

SRCDOSROOT=c:\\dev\\fmk\\kalk\\razdb\\1g\\

PRGS=fak_kal.prg fin.prg gen_fakt.prg ka_ka.prg kont_dok.prg tops.prg tops_ka.prg mnu_raz.prg imp_txt.prg

CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

