VERZIJA=CDX
MODUL=ka_p1rpt


SRCDOSROOT=c:\\dev\\fmk\\kalk\\prod\\rpt\\1g\\

PRGS=frm_kpro.prg mnu_izvj.prg rpt_81.prg rpt_alo.prg rpt_all.prg rpt_fllp.prg rpt_ip.prg rpt_kpro.prg rpt_llp.prg rpt_llps.prg rpt_olpp.prg rpt_rflp.prg rpt_rrp.prg rpt_rup.prg

CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

