VERZIJA=CDX
MODUL=ka_s1is


SRCDOSROOT=c:\\dev\\fmk\\kalk\\specif\\inters\\1g\\

PRGS=frm_24.prg

CS=
ASMS=

OBJS=$(OBJPRGS) $(OBJCS) $(OBJASMS)

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

