VERZIJA=CDX
MODUL=ka_s1is


SRCDOSROOT=$(BASEDOS)\\fmk\\kalk\\specif\\inters\\1g\\

PRGS=frm_24.prg

CS=
ASMS=

OBJS=$(OBJPRGS) $(OBJCS) $(OBJASMS)

include ../../../../fmk_lib/Makefile_clipper

