VERZIJA=CDX
MODUL=ka_1pr

SRCDOSROOT=c:\\dev\\fmk\\kalk\\proizvod\\1g\\

PRGS=fak_kal.prg frm_pr.prg frm_rn.prg frmg_rn.prg gen_dok.prg rpt_pr.prg rpt_rn.prg tops_ka.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
