VERZIJA=CDX
MODUL=ka_1pr

SRCDOSROOT=$(BASEDOS)\\fmk\\kalk\\proizvod\\1g\\

PRGS=fak_kal.prg frm_pr.prg frm_rn.prg frmg_rn.prg gen_dok.prg rpt_pr.prg rpt_rn.prg tops_ka.prg rpt_prs.prg
CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper
